spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**
        - id: seat
          uri: http://localhost:8082
          predicates:
            - Path=/seats/**
        - id: payment
          uri: http://localhost:8086
          predicates:
            - Path=/payments/**

---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order5
          uri: http://order5:8080
          predicates:
            - Path=/orders/**
        - id: seat5
          uri: http://seat5:8080
          predicates:
            - Path=/seats/ui/index.html
        - id: payment5
          uri: http://payment5:8080
          predicates:
            - Path=/payments/**
